version: '3.8'
services:
  app:
    build: .
    environment:
      - MODEL_NAME=sentence-transformers/all-MiniLM-L6-v2
    ports:
      - "8000:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000
